# Copyright (c) Ollion
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: copywrite-headers
        name: copywrite-headers
        entry: copywrite headers
        language: system
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail'
        language: system
        stages: ["commit", "push"]
