# Copyright (c) CloudCover
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: copywrite-headers
        name: copywrite-headers
        entry: copywrite headers
        language: system
