# Configuration System:
#
# The project uses the Viper library to manage its configuration system.
# The configuration values can be accessed using dot notation, where nested object and array values can be referred to using dot notation in the project.
# For example, to access the value of the 'host' property in the 'db' object, you can use `viper.GetString("db.host")`.
#
# Environment Variable Configuration:
#
# To set these configuration values using environment variables, you need to use the project prefix "TR" followed by an underscore (_) as a separator.
# For example, to set the value of 'host' property in the 'db' object using an environment variable, you would use "TR_DB_HOST".
#
# Default Configuration:
#
# The following is the default configuration:

db:
  host: "localhost"      # db host name
  user: "postgres"       # db username
  # password:            # db password no default, panic if not set.
  name: "cc_terrarium"   # database name
  port: 5432             # db port
  ssl_mode: false        # enable SSL mode
  type: postgres         # type of db - postgres | sqlite
  dsn: embedded.db       # SQLite Data Source Name
  retry_attempts: 20     # max number of re-tries on connection request failure
  retry_interval_sec: 2  # time to wait for (in seconds) before each retry
  retry_jitter_sec: 2    # additional random time (in seconds) between 0 and this, to be added to the wait time

log:
  format: "JSON"        # log format - text | json
  level: "info"         # maximum log level - debug | info | warn | error | fatal
  pretty_print: false   # format the text log using colors and indentation etc.

server:
  http_port: 3000
  grpc_port: 10000
