name: Run CI Checks

on:
  pull_request:
    branches: ["main"]

env:
  TR_DB_PASSWORD: a_super_secret_sequence_of_ordinary_characters

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check default Setup
        run: |
          make docker-init
          make farm-release-pull || echo "Terrarium farm release not found. Skipping farm DB check"
          make docker-build docker-run
          sleep 10
          curl --fail -s http://localhost:3000/v0/healthcheck
          make docker-stop-clean

      - name: Run unit tests
        run: |
          rm -f data/cc_terrarium.psql
          make docker-stop-clean docker-api-test

      - name: Check harvest script
        run: |
          rm -f data/cc_terrarium.psql
          make docker-stop-clean docker-harvest
