name: Run CI Checks

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  TR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check default Setup
        run: |
          make farm-release-pull
          make docker-init docker-build docker-run
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: API Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:3000/v0/healthcheck
          max-attempts: 60
          retry-delay: 1s
          retry-all: true

      - name: Run unit tests
        run: |
          rm -f data/cc_terrarium.psql
          make docker-stop-clean docker-api-test

      - name: Check harvest script
        run: |
          rm -f data/cc_terrarium.psql
          make docker-stop-clean docker-harvest
