name: Terrarium CLI Release

on:
  push:
    tags:
    - 'v0.*'

permissions:
    contents: write
    packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install xgo
        run: |
          go install src.techknowlogick.com/xgo@latest
      - name: Install goreleaser
        uses: supplypike/setup-bin@v3
        with:
          uri: https://github.com/cldcvr/goreleaser/releases/download/v0.1/goreleaser_Linux_x86_64.tar.gz
          name: 'goreleaser'
          version: 'v0.1'
      - name: Create release artifacts
        run: |
          ./scripts/create-release-artifacts.sh ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
